name: Android Arch
url: http://badhrinath.github.io/androidarch.blog
description: A blog by an android evangelist

permalink: /:year/:month/:day/:title/
paginate: 5
pygments: true
excerpt_separator: "<!-- more -->"

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
# Build settings
#theme: jekyll-theme-architect
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/