name: Appdroidlab
url: http://appdroidlab.github.io
description: A blog by an android evangelist

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true
excerpt_separator: "<!-- more -->"

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']