name: Android Arch
url: http://cbadhrinath.github.io
description: A blog by an android evangelist

permalink: /:year/:month/:day/:title/
paginate: 5
pygments: true
excerpt_separator: "<!-- more -->"

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']